FROM node:20-slim AS base

FROM base AS builder
WORKDIR /usr/app
COPY ./package*.json ./
RUN npm install
COPY . .

FROM base AS runner
WORKDIR /usr/app
COPY --from=builder /usr/app/public ./public
USER node
EXPOSE 3000
CMD
