name: 🌐 Frontend action
description: This action builds, tests, and pushes the frontend Docker image.

inputs:
  tag:
    description: The tag to push to the Docker registry.
    required: true
  dockerhub_username:
    description: The username for my docker account.
    required: true
  dockerhub_token: 
    description: The token for my docker account.
    required: true
  folder: 
    description: The folder where resides the dockerfile.
    required: true

runs:
  using: composite
  steps:
      - name: install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.0.5
      - uses: actions/setup-node@v4
        with:
          node-version: 20.11.1
          cache: 'pnpm'
          cache-dependency-path: './frontend/pnpm-lock.yaml'
      - name: Install dependencies
        working-directory: ./frontend
        run: pnpm install
        shell: bash
      - name: Build SvelteKit project
        working-directory: ./frontend
        run: pnpm run build  # or pnpm prepare
        shell: bash
      - name: Cache .svelte-kit and node_modules
        uses: actions/cache@v3
        with:
          path: |
            ./frontend/.svelte-kit
            ./frontend/node_modules
          key: ${{ runner.os }}-svelte-kit-${{ hashFiles('frontend/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-svelte-kit-#
      # - name: 🔬 Lint
      #   working-directory: ./frontend
      #   run: pnpm run lint
      # - name: 🔎 Type check
      #   working-directory: ./frontend
      #   run: pnpm run check
      # - name: Update apt and install dependencies
      #   working-directory: ./frontend
      #   run: |
      #     apt-get update
      #     apt-get install -y libenchant-dev libicu-dev libjpeg-turbo-official32=2.2 libvpx-dev libevent-dev
      # - name: Install playwright browsers
      #   working-directory: ./frontend
      #   run: pnpm exec playwright install --with-deps
      # - name: 🔎 Integration test
      #   working-directory: ./frontend
      #   run: pnpm run test:integration
      - name: 🔎 Unit test
        working-directory: ./frontend
        run: pnpm run test:unit
        shell: bash
      - name: Push frontend docker application to container registry
        uses: ./.github/actions/utility-actions/push-docker-image
        with:
          tag: ${{ inputs.tag }}
          dockerhub_username: ${{ inputs.dockerhub_username }}
          dockerhub_token: ${{ inputs.dockerhub_token }}
          folder: ${{ inputs.folder }}
