name: 🛠️Run pnpm install
description: Install pnpm then install project's dependencies

runs:
  using: 'composite'
  steps:
      - name: install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.0.5
      - uses: actions/setup-node@v4
        with:
          node-version: 20.11.1
          cache: 'pnpm'
          cache-dependency-path: './frontend/pnpm-lock.yaml'
      - name: Install dependencies
        working-directory: ./frontend
        run: pnpm install
        shell: bash

