# NOTE: The example for using the docker compose option.
# TODO: Make that complete when you have both the frontend and the backend

version: "3.8" # Where to find that ?
services:
  web: 
    depends_on:
      - api
    build: ./frontend/
    container_name: frontend
    ports:
      - 5173:5173  
    environment:
      VITE_API_URL: http://localhost:8000
    develop: # for the docker compose watch mode
      watch: 
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/package-lock.json
          action: rebuild
        - path: ./frontend/
          target: /app
          action: sync
  api:
    depends_on:
      - db
    build: ./backend/
    container_name: api
    ports:
      - 8080:8080  
    environment: 
      PORT: 3500
    develop: # for the docker compose watch mode
      # TODO: Change that with the correct  setup for a golang backend
      watch: 
        - path: ./backend/go.mod
          action: rebuild
        - path: ./backend/go.sum
          action: rebuild
        - path: ./backend/
          target: /app
          action: sync
  generaldb:
    build: "."
    container_name: sqlite-container
    image: alpine:latest
    environment: 
      database-name: "event-reservation-app"
    ports:
      - 27017:27017  
    volumes:
      - sqlite-container:/data/db

  redis:
    image: redis:latest
    container_name: redis_session
    environment:
      REDIS_USER: root 
      REDIS_PASSWORD: root 
    ports:
      - 6789

