version: "3.8"
services:
  frontend: 
    depends_on:
      - backend
    container_name: frontend
    image: henga/event-reservation-app:frontend
    restart: always
    environment: 
      - ORIGIN=http://localhost:3000
    ports:
      - 3000:3000  

  backend:
    depends_on:
      - redis
    container_name: backend
    image: henga/event-reservation-app:backend
    ports:
      - 3500:3500  
    environment: 
      - PORT=3500
      - APP_ENV=production

  redis:
    image: redis:latest
    container_name: session-manager
    command: redis-server --requirepass secret
    ports:
      - 6379:6379
