FROM golang:1.22.1-alpine AS builder

RUN apk add --no-cache build-base

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .

RUN CGO_ENABLED=1 GOOS=linux go build -ldflags="-s" -v -o myapp ./cmd/event-reservation-app/*.go

FROM alpine:latest

RUN apk add --no-cache sqlite

WORKDIR /app

COPY --from=builder /app/myapp .
COPY --from=builder /app/internal/sqlite/migrations ./internal/sqlite/migrations
COPY --from=builder /app/*.env ./

EXPOSE 3500

CMD ["./myapp", "-port", "3500"]
