# vars
# IMAGE_NAME := "henga/event-reservation-app"## The name of the docker image for the frontend part of the project
#
# ifneq (,$(wildcard ./example.env.env))
#     include example.env
#     export
# endif
#
# .PHONY: help run dev build start test test-unit test-integration
#
# .DEFAULT_GOAL := help
#
# help:
# 	@../help.sh "$(MAKEFILE_LIST)"
#
#
# dev:
#
# build:
#
# start:
#
# test: test-unit test-integration test-e2e
#
# test-unit:
#
# test-integration:
#
# # helpers
