name: 🧪 Go Test Suite
description: Run Go test suite with CGO enabled

inputs:
  go-version:
    description: Version of Go to use for testing
    default: '1.22.1'
  test-path:
    description: Path pattern for test files
    default: './...'

runs:
  using: composite
  steps:
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}

    - name: Setup test dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y ca-certificates build-essential
        sudo update-ca-certificates

    - name: Run tests
      shell: bash
      env:
        CGO_ENABLED: 1
        GOOS: linux
      run: |
        cd backend
        go test ${{ inputs.test-path }}
