name: 🌐 Backend action
description: This action builds, tests, and pushes the backend Docker image.

inputs:
  go-version:
    description: The version of Go to use.
    required: true
  build-path:
    description: The path to the build directory.
    required: true
  test-path:
    description: The path to the test directory.
    required: true
  output-name:
    description: The name of the output file.
    required: true
  tag:
    description: The tag to push to the Docker registry.
    required: true
  dockerhub_username:
    description: The username for my docker account.
    required: true
  dockerhub_token: 
    description: The token for my docker account.
    required: true
  folder: 
    description: The folder where resides the dockerfile.
    required: true

runs:
  using: composite
  steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go-version }}

      - name: Setup test dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates build-essential
          sudo update-ca-certificates

      - name: ⬣ Build application
        shell: bash
        env:
          CGO_ENABLED: 1
          GOOS: linux
        run: |
          cd backend
          go build -ldflags="-s" -v -o ${{ inputs.output-name }} ${{ inputs.build-path }}
      - name: 🧪 Golang tests
        shell: bash
        env:
          CGO_ENABLED: 1
          GOOS: linux
        run: |
          cd backend
          go test ${{ inputs.test-path }}
      - name: Push backend docker application to container registry
        uses: ./.github/actions/utility-actions/push-docker-image
        with:
          tag: ${{ inputs.tag }}
          dockerhub_username: ${{ inputs.dockerhub_username }}
          dockerhub_token: ${{ inputs.dockerhub_token }}
          folder: ${{ inputs.folder }}
