name: ⬣ Go Build
description: Build Go application with CGO enabled and prepare for Linux deployment

inputs:
  go-version:
    description: Version of Go to use for building
    default: '1.22.1'
  build-path:
    description: Path to the main Go files to build
    default: './cmd/event-reservation-app/*.go'
  output-name:
    description: Name of the output binary
    default: 'leviosa'

runs:
  using: composite
  steps:
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}

    - name: Setup build dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y ca-certificates build-essential
        sudo update-ca-certificates

    - name: Build application
      shell: bash
      env:
        CGO_ENABLED: 1
        GOOS: linux
      run: go build -ldflags="-s" -v -o ${{ inputs.output-name }} ${{ inputs.build-path }}
