name: 🚀 Deploy application
on:
  workflow_run:
    workflows: ["🌐 Front", "🛢Back"]
    types:
      - completed

jobs:
  deploy:
    name: 🚀 Deploy
    runs-on: [self-hosted]
    needs: [front, back]
    # only build/deploy main branch on pushes
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4.1.1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run docker-compose in production mode
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          APP_ENV: ${{ secrets.APP_ENV}}
          AWS_REGION: ${{ secrets.AWS_REGION }key}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          GMAIL_EMAIL: ${{ secrets.GMAIL_EMAIL }}
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
        run: |
          docker pull henga/event-reservation-app:frontend
          docker pull henga/event-reservation-app:backend
          docker-compose -d up --build 
          docker system prune --all --volumes --force
          # TODO: use the health endpoint to check if the repo works fine
