name: 🚀 Deploy production application

on:
  workflow_run:
    workflows: ["🌐 Front", "🛢 Back"]
    types:
      - completed

jobs:
  deploy:
    name: 🚀 Deploy production
    runs-on: [self-hosted]
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.workflow_id != github.run_id
    steps:
      - uses: ./.github/actions/deploy
        with:
          filter: 'production'
          app_env: 'production'
          backend_port: 3500
          port: 3000
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
          compose_file: 'Compose'
          public_url: 'https://leviosa.care'
          aws_region: ${{ secrets.AWS_REGION }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          stripe_secret_key: ${{ secrets.STRIPE_SECRET_KEY }}
          gmail_email: ${{ secrets.GMAIL_EMAIL }}
          gmail_password: ${{ secrets.GMAIL_PASSWORD }}
          google_client_id: ${{ secrets.GOOGLE_CLIENT_ID }}
          google_client_secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
