name: Run test for event-reservation-app

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  backend-test:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22.1
      - run: go test ./backend/tests/...
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: "backend_report"
          path: "backend_report/"
          retention-days: 30
